"""intake question depends_on

Revision ID: 403eb9d6f598
Revises: d12ef3e173a7
Create Date: 2026-07-20 19:15:41.750624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403eb9d6f598'
down_revision: Union[str, Sequence[str], None] = 'd12ef3e173a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_question', sa.Column('depends_on', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
    # Backfill the seeded question set on already-set-up instances (the seed
    # only runs once, at /setup). Uses the pack's canonical conditions.
    from cairn.seeds.intake import DEPENDS_ON

    table = sa.table(
        "intake_question", sa.column("code", sa.String), sa.column("depends_on", sa.JSON)
    )
    for code, condition in DEPENDS_ON.items():
        op.execute(
            table.update()
            .where(table.c.code == op.inline_literal(code))
            .values(depends_on=condition)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_question', 'depends_on')
    # ### end Alembic commands ###
