"""initial schema

Revision ID: 43cf623fcaef
Revises: 
Create Date: 2026-07-10 06:11:13.163841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cf623fcaef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # business_function and user have a mutual FK cycle (user.business_function_id ->
    # business_function.id; business_function.created_by/updated_by -> user.id). Create user
    # first without the business_function_id constraint, then business_function, then add the
    # deferred FK — required for FK-enforcing databases (Postgres); sqlite create_all resolves
    # this automatically but a linear migration script must do it explicitly.
    op.create_table('user',
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CONTRIBUTOR', 'CURATOR', 'APPROVER_DPO', 'VIEWER', name='role'), nullable=False),
    sa.Column('business_function_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_function',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user') as batch_op:
        batch_op.create_foreign_key(
            'fk_user_business_function_id', 'business_function', ['business_function_id'], ['id']
        )
    op.create_table('appropriate_policy_document',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('SCHEDULE1', 'S42_PART3', name='apdscope'), nullable=False),
    sa.Column('document_ref', sa.String(), nullable=False),
    sa.Column('retain_until', sa.Date(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_dsa',
    sa.Column('type', sa.Enum('CONTROLLER_PROCESSOR', 'JOINT_CONTROLLER', 'DATA_SHARING', name='contracttype'), nullable=False),
    sa.Column('art28_checklist_complete', sa.Boolean(), nullable=True),
    sa.Column('security_schedule', sa.Text(), nullable=True),
    sa.Column('sub_processor_authorisation', sa.Enum('NONE', 'GENERAL', 'SPECIFIC', name='subprocessorauthorisation'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_subject_category',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('le_classification', sa.Enum('SUSPECT', 'CONVICTED', 'VICTIM', 'WITNESS', 'OTHER', 'NONE', name='leclassification'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawful_basis_general',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('public_authority_restricted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lawful_basis_le',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('legal_entity',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('role_type', sa.Enum('OWN_ORG', 'JOINT_CONTROLLER', 'REPRESENTATIVE', 'DPO', 'PROCESSOR', 'SUB_PROCESSOR', 'DATA_SUPPLIER', 'PARTNER_AGENCY', name='legalentityroletype'), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_profile',
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('org_type', sa.Enum('PUBLIC_AUTHORITY', 'PRIVATE_BODY', 'MIXED', name='orgtype'), nullable=False),
    sa.Column('sector_pack', sa.String(), nullable=False),
    sa.Column('legal_entity_topology', sa.Enum('SINGLE', 'GROUP', 'JOINT', name='legalentitytopology'), nullable=False),
    sa.Column('applicable_regimes', sa.JSON(), nullable=False),
    sa.Column('active_modules', sa.JSON(), nullable=False),
    sa.Column('public_authority_guards', sa.Boolean(), nullable=False),
    sa.Column('commencement_watch', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_data_category',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_special_category', sa.Boolean(), nullable=False),
    sa.Column('is_criminal_offence', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy_notice',
    sa.Column('notice_version', sa.String(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('covers_art13', sa.Boolean(), nullable=False),
    sa.Column('covers_art14', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_activity',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('business_function_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Enum('OPERATIONAL', 'ANALYTICS_MODELLING', name='activitytype'), nullable=False),
    sa.Column('activity_domain', sa.Enum('FIRE_SAFETY_ENFORCEMENT', 'FIRE_INVESTIGATION', 'FIRESETTER_INTERVENTION', 'OTHER', name='activitydomain'), nullable=True),
    sa.Column('regime', sa.Enum('GENERAL', 'LAW_ENFORCEMENT', name='regime'), nullable=False),
    sa.Column('regime_source', sa.Enum('POLICY', 'MANUAL_OVERRIDE', name='regimesource'), nullable=False),
    sa.Column('regime_override_reason', sa.String(), nullable=True),
    sa.Column('controller_or_processor', sa.Enum('CONTROLLER', 'PROCESSOR', 'JOINT', name='controllerorprocessor'), nullable=False),
    sa.Column('record_status', sa.Enum('DRAFT', 'IN_REVIEW', 'ACTIVE', 'RETIRED', name='recordstatus'), nullable=False),
    sa.Column('lifecycle_stage', sa.Enum('TRIAL', 'LIVE', 'RETIRED', name='lifecyclestage'), nullable=False),
    sa.Column('trial_start', sa.Date(), nullable=True),
    sa.Column('trial_end', sa.Date(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('categories_of_processing', sa.Text(), nullable=True),
    sa.Column('personal_data_source', sa.JSON(), nullable=False),
    sa.Column('is_statutory_task', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('last_reviewed_at', sa.Date(), nullable=True),
    sa.Column('next_review_at', sa.Date(), nullable=False),
    sa.Column('vulnerable_or_safeguarding_flag', sa.Boolean(), nullable=False),
    sa.Column('children_flag', sa.Boolean(), nullable=False),
    sa.Column('external_data_use_mode', sa.Enum('NONE', 'MANUAL', 'AUTOMATED', name='externaldatausemode'), nullable=False),
    sa.Column('lineage_granularity', sa.Enum('ACTIVITY', 'RECORD', name='lineagegranularity'), nullable=False),
    sa.Column('high_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('le_data_subject_classification', sa.JSON(), nullable=True),
    sa.Column('le_fact_vs_assessment_noted', sa.Boolean(), nullable=True),
    sa.Column('s62_logging_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_function.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_version',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('version_change_note', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regime_policy',
    sa.Column('activity_domain', sa.Enum('FIRE_SAFETY_ENFORCEMENT', 'FIRE_INVESTIGATION', 'FIRESETTER_INTERVENTION', 'OTHER', name='activitydomain'), nullable=False),
    sa.Column('assigned_regime', sa.Enum('GENERAL', 'LAW_ENFORCEMENT', name='regime'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_domain')
    )
    op.create_table('retention_rule',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('legal_driver', sa.Text(), nullable=True),
    sa.Column('disposal_method', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule1_condition',
    sa.Column('paragraph', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('needs_apd', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph')
    )
    op.create_table('schedule8_condition',
    sa.Column('paragraph', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph')
    )
    op.create_table('security_measure',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'ORGANISATIONAL', name='securitymeasurecategory'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_category_condition',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('needs_schedule1', sa.Boolean(), nullable=False),
    sa.Column('needs_apd', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('third_country',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('adequacy_status', sa.Enum('ADEQUATE', 'NOT_ADEQUATE', 'UNDER_REVIEW', name='adequacystatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_mechanism',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('activity_contract',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_dsa.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'contract_id')
    )
    op.create_table('activity_datacategory',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('data_subject_scope_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['personal_data_category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['data_subject_scope_id'], ['data_subject_category.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'category_id')
    )
    op.create_table('activity_datasubject',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('datasubject_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['datasubject_id'], ['data_subject_category.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'datasubject_id')
    )
    op.create_table('activity_feeds',
    sa.Column('source_activity_id', sa.String(), nullable=False),
    sa.Column('consumer_activity_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.CheckConstraint('source_activity_id != consumer_activity_id'),
    sa.ForeignKeyConstraint(['consumer_activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_activity_id', 'consumer_activity_id')
    )
    op.create_table('activity_privacynotice',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('privacynotice_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['privacynotice_id'], ['privacy_notice.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'privacynotice_id')
    )
    op.create_table('activity_retention',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('retention_rule_id', sa.String(), nullable=False),
    sa.Column('data_category_scope_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['data_category_scope_id'], ['personal_data_category.id'], ),
    sa.ForeignKeyConstraint(['retention_rule_id'], ['retention_rule.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'retention_rule_id', 'data_category_scope_id')
    )
    op.create_table('activity_security',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('security_measure_id', sa.String(), nullable=False),
    sa.Column('inherited_from_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['security_measure_id'], ['security_measure.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'security_measure_id')
    )
    op.create_table('breach_record',
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('reportable_to_ico', sa.Boolean(), nullable=False),
    sa.Column('individuals_notified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_record',
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('response_due', sa.Date(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Enum('UPHELD', 'PARTLY_UPHELD', 'NOT_UPHELD', 'WITHDRAWN', name='complaintoutcome'), nullable=True),
    sa.Column('ico_escalation_flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_party',
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('legal_entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_dsa.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entity.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'legal_entity_id')
    )
    op.create_table('decision_support_adm',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('use_mode', sa.Enum('MANUAL', 'AUTOMATED', name='admusemode'), nullable=False),
    sa.Column('technique', sa.Text(), nullable=True),
    sa.Column('solely_automated', sa.Boolean(), nullable=True),
    sa.Column('significant_effects', sa.Boolean(), nullable=True),
    sa.Column('accuracy_bias_checks', sa.Text(), nullable=True),
    sa.Column('human_review', sa.Text(), nullable=True),
    sa.Column('contestability', sa.Text(), nullable=True),
    sa.Column('transparency_ref', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['transparency_ref'], ['privacy_notice.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dpia',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('screening_outcome', sa.Enum('REQUIRED', 'NOT_REQUIRED', 'DOCUMENTED_NOT_REQUIRED', name='screeningoutcome'), nullable=False),
    sa.Column('nature_scope_context_purposes', sa.Text(), nullable=True),
    sa.Column('necessity_proportionality', sa.Text(), nullable=True),
    sa.Column('risks_to_individuals', sa.Text(), nullable=True),
    sa.Column('mitigations', sa.Text(), nullable=True),
    sa.Column('residual_risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='residualrisk'), nullable=True),
    sa.Column('dpo_advice', sa.Text(), nullable=True),
    sa.Column('sign_off_by', sa.String(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sign_off_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_data_source',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('supplier_legal_entity_id', sa.String(), nullable=True),
    sa.Column('supplier_role', sa.Enum('PROCESSOR', 'SEPARATE_CONTROLLER', name='supplierrole'), nullable=True),
    sa.Column('agreement_ref', sa.String(), nullable=True),
    sa.Column('special_category', sa.Enum('NONE', 'INFERRED', 'DIRECT', name='sourcespecialcategory'), nullable=False),
    sa.Column('art14_relationship', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_legal_entity_id'], ['legal_entity.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawful_basis_record',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('regime_scope', sa.Enum('PART2', 'PART3', name='regimescope'), nullable=False),
    sa.Column('art6_basis_id', sa.String(), nullable=True),
    sa.Column('art6_justification', sa.Text(), nullable=True),
    sa.Column('art9_condition_id', sa.String(), nullable=True),
    sa.Column('schedule1_condition_id', sa.String(), nullable=True),
    sa.Column('art10_basis', sa.String(), nullable=True),
    sa.Column('s35_basis_id', sa.String(), nullable=True),
    sa.Column('schedule8_condition_id', sa.String(), nullable=True),
    sa.Column('apd_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['apd_id'], ['appropriate_policy_document.id'], ),
    sa.ForeignKeyConstraint(['art6_basis_id'], ['lawful_basis_general.id'], ),
    sa.ForeignKeyConstraint(['art9_condition_id'], ['special_category_condition.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['s35_basis_id'], ['lawful_basis_le.id'], ),
    sa.ForeignKeyConstraint(['schedule1_condition_id'], ['schedule1_condition.id'], ),
    sa.ForeignKeyConstraint(['schedule8_condition_id'], ['schedule8_condition.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'regime_scope')
    )
    op.create_table('recipient',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INTERNAL', 'PROCESSOR', 'JOINT_CONTROLLER', 'PUBLIC_BODY', 'OTHER', name='recipienttype'), nullable=False),
    sa.Column('legal_entity_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entity.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_asset',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('hosting_country', sa.String(), nullable=True),
    sa.Column('default_retention_id', sa.String(), nullable=True),
    sa.Column('s62_logging_in_scope', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['default_retention_id'], ['retention_rule.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_datasource',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['external_data_source.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'source_id')
    )
    op.create_table('activity_recipient',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'recipient_id')
    )
    op.create_table('activity_system',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system_asset.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'system_id')
    )
    op.create_table('adm_datasource',
    sa.Column('adm_record_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['adm_record_id'], ['decision_support_adm.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['external_data_source.id'], ),
    sa.PrimaryKeyConstraint('adm_record_id', 'source_id')
    )
    op.create_table('consent_record',
    sa.Column('lawful_basis_record_id', sa.String(), nullable=False),
    sa.Column('consented_to', sa.Text(), nullable=False),
    sa.Column('wording_shown', sa.Text(), nullable=False),
    sa.Column('consent_datetime', sa.DateTime(), nullable=False),
    sa.Column('consent_method', sa.Enum('ONLINE_FORM', 'PAPER', 'VERBAL_LOGGED', 'OTHER', name='consentmethod'), nullable=False),
    sa.Column('withdrawal_status', sa.Enum('ACTIVE', 'WITHDRAWN', name='withdrawalstatus'), nullable=False),
    sa.Column('withdrawal_datetime', sa.DateTime(), nullable=True),
    sa.Column('review_due', sa.Date(), nullable=True),
    sa.Column('age_check_outcome', sa.Enum('ADULT', 'CHILD_OVER_13', 'CHILD_UNDER_13', 'UNKNOWN', name='agecheckoutcome'), nullable=True),
    sa.Column('parental_consent_captured', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lawful_basis_record_id'], ['lawful_basis_record.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('externaldatasource_datacategory',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['personal_data_category.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['external_data_source.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'category_id')
    )
    op.create_table('lia_rli_record',
    sa.Column('lawful_basis_record_id', sa.String(), nullable=False),
    sa.Column('interest_identified', sa.Text(), nullable=False),
    sa.Column('necessity_test', sa.Text(), nullable=False),
    sa.Column('balancing_test', sa.Text(), nullable=True),
    sa.Column('safeguards', sa.Text(), nullable=True),
    sa.Column('decision', sa.Enum('PROCEED', 'DO_NOT_PROCEED', name='liadecision'), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lawful_basis_record_id'], ['lawful_basis_record.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_securitymeasure',
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('security_measure_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['security_measure_id'], ['security_measure.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system_asset.id'], ),
    sa.PrimaryKeyConstraint('system_id', 'security_measure_id')
    )
    op.create_table('transfer',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('third_country_id', sa.String(), nullable=False),
    sa.Column('mechanism_id', sa.String(), nullable=False),
    sa.Column('data_protection_test', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mechanism_id'], ['transfer_mechanism.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.ForeignKeyConstraint(['third_country_id'], ['third_country.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('system_securitymeasure')
    op.drop_table('lia_rli_record')
    op.drop_table('externaldatasource_datacategory')
    op.drop_table('consent_record')
    op.drop_table('adm_datasource')
    op.drop_table('activity_system')
    op.drop_table('activity_recipient')
    op.drop_table('activity_datasource')
    op.drop_table('system_asset')
    op.drop_table('recipient')
    op.drop_table('lawful_basis_record')
    op.drop_table('external_data_source')
    op.drop_table('dpia')
    op.drop_table('decision_support_adm')
    op.drop_table('contract_party')
    op.drop_table('complaint_record')
    op.drop_table('breach_record')
    op.drop_table('activity_security')
    op.drop_table('activity_retention')
    op.drop_table('activity_privacynotice')
    op.drop_table('activity_feeds')
    op.drop_table('activity_datasubject')
    op.drop_table('activity_datacategory')
    op.drop_table('activity_contract')
    op.drop_table('transfer_mechanism')
    op.drop_table('third_country')
    op.drop_table('special_category_condition')
    op.drop_table('security_measure')
    op.drop_table('schedule8_condition')
    op.drop_table('schedule1_condition')
    op.drop_table('retention_rule')
    op.drop_table('regime_policy')
    op.drop_table('record_version')
    op.drop_table('processing_activity')
    op.drop_table('privacy_notice')
    op.drop_table('personal_data_category')
    op.drop_table('organisation_profile')
    op.drop_table('legal_entity')
    op.drop_table('lawful_basis_le')
    op.drop_table('lawful_basis_general')
    op.drop_table('data_subject_category')
    op.drop_table('contract_dsa')
    op.drop_table('audit_event')
    op.drop_table('appropriate_policy_document')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('fk_user_business_function_id', type_='foreignkey')
    op.drop_table('business_function')
    op.drop_table('user')
    # ### end Alembic commands ###
