"""add activity_controller junction

Revision ID: 71180af7a9f3
Revises: 43cf623fcaef
Create Date: 2026-07-10 12:46:57.058101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71180af7a9f3'
down_revision: Union[str, Sequence[str], None] = '43cf623fcaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_controller',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('legal_entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entity.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'legal_entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_controller')
    # ### end Alembic commands ###
