"""intake wizard tables

Revision ID: 8f95f429124e
Revises: af99b1f9012f
Create Date: 2026-07-17 06:45:11.046657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f95f429124e'
down_revision: Union[str, Sequence[str], None] = 'af99b1f9012f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "TEXT", "TEXTAREA", "YES_NO", "DATE", "SINGLE_CHOICE", "MULTI_CHOICE", "VOCAB_MULTI",
        name="intakeanswerkind",
    ).create(op.get_bind(), checkfirst=True)
    sa.Enum("IN_PROGRESS", "SUBMITTED", "CANCELLED", name="intakestatus").create(
        op.get_bind(), checkfirst=True
    )
    op.create_table('intake_question',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('answer_kind', sa.Enum('TEXT', 'TEXTAREA', 'YES_NO', 'DATE', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'VOCAB_MULTI', name='intakeanswerkind'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('populates', sa.String(), nullable=True),
    sa.Column('enforcement_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('intake_submission',
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('business_function_id', sa.String(), nullable=False),
    sa.Column('respondent_id', sa.String(), nullable=False),
    sa.Column('respondent_contact', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'CANCELLED', name='intakestatus'), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_function.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_gap',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('question_code', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['processing_activity.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['intake_submission.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intake_gap')
    op.drop_table('intake_submission')
    op.drop_table('intake_question')
    sa.Enum(name="intakestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="intakeanswerkind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
