"""vocab entry status

Revision ID: 90c4514cc969
Revises: 71180af7a9f3
Create Date: 2026-07-11 05:57:57.497685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c4514cc969'
down_revision: Union[str, Sequence[str], None] = '71180af7a9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PROPOSED", "APPROVED", "REJECTED", name="entrystatus").create(
        op.get_bind(), checkfirst=True
    )
    op.add_column('data_subject_category', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    op.add_column('external_data_source', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    op.add_column('personal_data_category', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    op.add_column('recipient', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    op.add_column('retention_rule', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    op.add_column('security_measure', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    op.add_column('system_asset', sa.Column('entry_status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='entrystatus'), nullable=False, server_default='APPROVED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_asset', 'entry_status')
    op.drop_column('security_measure', 'entry_status')
    op.drop_column('retention_rule', 'entry_status')
    op.drop_column('recipient', 'entry_status')
    op.drop_column('personal_data_category', 'entry_status')
    op.drop_column('external_data_source', 'entry_status')
    op.drop_column('data_subject_category', 'entry_status')
    sa.Enum(name="entrystatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
