"""questionnaire import batch

Revision ID: a804f5480e39
Revises: df9665fbda6d
Create Date: 2026-07-11 10:43:36.265412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a804f5480e39'
down_revision: Union[str, Sequence[str], None] = 'df9665fbda6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "CONFIRMED", "CANCELLED", name="importbatchstatus").create(
        op.get_bind(), checkfirst=True
    )
    op.create_table('import_batch',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='importbatchstatus'), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_batch')
    sa.Enum(name="importbatchstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
