"""duaa children and further processing fields

Revision ID: af99b1f9012f
Revises: a804f5480e39
Create Date: 2026-07-11 21:41:41.496329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af99b1f9012f'
down_revision: Union[str, Sequence[str], None] = 'a804f5480e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_activity', sa.Column('is_further_processing', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('processing_activity', sa.Column('further_processing_note', sa.Text(), nullable=True))
    op.add_column('processing_activity', sa.Column('online_childrens_service_flag', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('processing_activity', sa.Column('childrens_matters_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_activity', 'childrens_matters_note')
    op.drop_column('processing_activity', 'online_childrens_service_flag')
    op.drop_column('processing_activity', 'further_processing_note')
    op.drop_column('processing_activity', 'is_further_processing')
    # ### end Alembic commands ###
