"""intake gap resolution note

Revision ID: fc08e7c30aac
Revises: 8f95f429124e
Create Date: 2026-07-17 07:02:17.481855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc08e7c30aac'
down_revision: Union[str, Sequence[str], None] = '8f95f429124e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_gap', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_gap', 'resolution_note')
    # ### end Alembic commands ###
